# Generated by Django 4.2.4 on 2023-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mc_donalds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="amount",
            field=models.IntegerField(db_column="amount", default=1),
        ),
        migrations.RenameField(
            model_name="productorder", old_name="amount", new_name="_amount",
        ),
    ]
