# Generated by Django 5.1.1 on 2024-09-25 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ad",
                    models.CharField(db_index=True, max_length=56, unique=True),
                ),
                ("text_ad", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=64, unique=True)),
                ("category_des", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AdCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_through",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="D16_MMORPG_board.advertisement",
                    ),
                ),
                (
                    "category_trough",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="D16_MMORPG_board.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advertisement",
            name="category_ad",
            field=models.ManyToManyField(
                related_name="ads",
                through="D16_MMORPG_board.AdCategory",
                to="D16_MMORPG_board.category",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_rating", models.SmallIntegerField(default=0)),
                (
                    "comment_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="D16_MMORPG_board.advertisement",
                    ),
                ),
                (
                    "comment_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_authors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_avatar",
                    models.ImageField(default="default.jpg", upload_to="img/users/"),
                ),
                ("user_phone", models.CharField(default="+7000000000", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
