# Generated by Django 5.1.1 on 2024-09-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_des",
            field=models.TextField(blank=True),
        ),
    ]
