# Generated by Django 5.1.1 on 2024-09-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0002_alter_category_category_des"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="category_des", new_name="category_desc",
        ),
    ]
