# Generated by Django 5.1.1 on 2024-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0003_rename_category_des_category_category_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="category_ad",
            field=models.ManyToManyField(
                related_name="category",
                through="D16_MMORPG_board.AdCategory",
                to="D16_MMORPG_board.category",
            ),
        ),
    ]
