# Generated by Django 5.1.1 on 2024-09-27 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "D16_MMORPG_board",
            "0005_rename_category_ad_advertisement_ad_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="ad_update",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="ad_category",
            field=models.ManyToManyField(
                related_name="Category",
                through="D16_MMORPG_board.AdCategory",
                to="D16_MMORPG_board.category",
            ),
        ),
    ]
