# Generated by Django 5.1.1 on 2024-09-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0006_advertisement_ad_update_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="advertisement", name="ad_category",),
        migrations.DeleteModel(name="AdCategory",),
        migrations.AddField(
            model_name="advertisement",
            name="ad_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="D16_MMORPG_board.category",
            ),
        ),
    ]
