# Generated by Django 5.1.1 on 2024-09-28 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "D16_MMORPG_board",
            "0007_remove_advertisement_ad_category_delete_adcategory_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="comment_user",),
        migrations.AddField(
            model_name="advertisement",
            name="ad_author",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_author",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_authors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
