# Generated by Django 5.1.2 on 2024-11-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0015_profile_user_subscriber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_subscriber",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
