# Generated by Django 5.1.2 on 2024-11-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0016_alter_profile_user_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_subscriber",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
