# Generated by Django 5.1.2 on 2024-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0017_alter_profile_user_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_avatar",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="img/users/"
            ),
        ),
    ]
