# Generated by Django 5.1.2 on 2024-11-12 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0018_alter_profile_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="reply_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
