# Generated by Django 5.1.2 on 2024-11-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0019_reply_reply_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply", name="reply_status", field=models.BooleanField(),
        ),
    ]
