# Generated by Django 5.1.2 on 2024-11-16 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0020_alter_reply_reply_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="reply_ad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="D16_MMORPG_board.advertisement",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="reply_author",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies_authors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
