# Generated by Django 5.1.2 on 2024-11-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D16_MMORPG_board", "0021_alter_reply_reply_ad_alter_reply_reply_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="ad_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="reply",
            name="reply_status",
            field=models.BooleanField(default=False),
        ),
    ]
