# Generated by Django 4.2.4 on 2023-09-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="category",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Post",),
    ]
